### ISSUE TITLE
Using timers in Encoder Mode

### ISSUE THREAD

**Issue by d-a-v** [khoih-prog/Portenta_H7_TimerInterrupt#2]
### Is your feature request related to a problem?

No problem with the current version of this library, the "encoder mode" seems to be not implemented yet.

### Describe the solution you'd like

A pure hardware version for dealing with encoders is welcome.

### Describe alternatives you've considered

Using the official "MachineControl" library is not efficient.

Additional context
=====================

Hello,

We were having a look to the H7 ability to use encoders hardware entries like presented in this [tutorial](https://deepbluembedded.com/stm32-timer-encoder-mode-stm32-rotary-encoder-interfacing/).

We are using Arduino, and already tried their pure [software implementation](https://github.com/arduino-libraries/Arduino_MachineControl/tree/master/examples/Encoders).
It is [unfortunately too slow](https://github.com/arduino-libraries/Arduino_MachineControl/blob/master/src/utility/QEI/QEI.cpp) for our needs.

Then we found your library which looks very good at playing with timers.
There is no example dealing with encoders .
How hard do you think it would be to add this encoder mode to your timers HAL ?

Thanks for any information

**Comment by khoih-prog** [comment]
Hi @d-a-v 

That seems **interesting**, but I'm sorry I have no bandwidth to finish this now.

But it seems the encoder is based on well written **QEI** (Quadrature Encoder Interface) code. You have to read the  QEI source code to use the encoder efficiently, not following the so simple example [**Encoders**](https://github.com/arduino-libraries/Arduino_MachineControl/blob/master/examples/Encoders/Encoders.ino)

IMHO, it's also not so complicated to even write a new library to deal with this Encoder feature efficiently.

I suggest you post on the [**Arduino_MachineControl** issues](https://github.com/arduino-libraries/Arduino_MachineControl/issues) or Arduino Forum to ask for help.

I'm closing this now as I currently don't have any intention and time to add this feature to this library. Certainly, any contribution to add the feature will be appreciated.

Good Luck,
